%YAML 1.1
--- 
# Suricata Custom Configuration

# Network Settings
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    TELNET_SERVERS: "$HOME_NET"

# Output Configuration
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert:
            payload: yes
            packet: yes
            http-body: no
            http-header: yes
            tagged-packets: yes
        - http:
            extended: yes
        - dns:
            query: yes
            answer: yes
        - tls:
            extended: yes
        - files:
            force-magic: no
        - drop:
            alerts: yes
        - smtp:
            extended: yes
        - ssh
        - stats:
            totals: yes
            threads: no
            deltas: no
        - flow

# Application Layer Protocols
app-layer:
  protocols:
    tls:
      enabled: yes
    http:
      enabled: yes
    ssh:
      enabled: yes
    smtp:
      enabled: yes
    dns:
      tcp:
        enabled: yes
      udp:
        enabled: yes

# Detection Engine Settings
detect-engine:
  - profile: medium
  - inspection-recursion-limit: 3000
  - prefilter:
      default: mpm

# Advanced Settings
advanced-settings:
  - stats:
      enabled: yes
      interval: 10
  - nfq:
      repeat: no
      repeat-mark: 0
